### ISSUE TITLE
missing 1 required positional argument: 'is_partition'

### ISSUE THREAD

**Issue by madzul** [farhan0581/django-inspectdb-refactor#9]
Doesn't work for Django 2.2.7

`File "/usr/local/lib/python3.7/site-packages/inspectdb_refactor/management/commands/inspectdb_refactor.py", line 270, in handle_inspection for meta_line in self.get_meta(table_name, constraints, column_to_field_name, is_view):
TypeError: get_meta() missing 1 required positional argument: 'is_partition'`

**Comment by iamadhihere** [comment]
I'm too facing the issue

File "C:\Users\HP\Anaconda3\lib\site-packages\inspectdb_refactor\management\commands\inspectdb_refactor.py", line 270, in handle_inspection
    for meta_line in self.get_meta(table_name, constraints, column_to_field_name, is_view):
TypeError: get_meta() missing 1 required positional argument: 'is_partition'

**Comment by madzul** [comment]
I've manage to solve this issue by using the github's version (not the one from pypi).
This issue could be close.
